---
services:
  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    depends_on:
      - postgres
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_APP:     run.py
      FLASK_DB_TYPE: postgres       # Use postgres
      FLASK_DB_USER: postgres       # Usuário do banco
      FLASK_DB_NAME: postgres       # Nome do Banco
      FLASK_DB_PASSWORD: secretpass # Senha do banco
      FLASK_DB_HOST: postgres       # Hostname
      FLASK_DB_PORT: 5432           # Porta
    networks:
      - backend
      - frontend

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost/api
    depends_on:
      - backend 
    networks:
      - frontend
     
volumes:
  pg_data:

networks:
  frontend:  
  backend: